#docker build -t mam10eks/roberta-sentiment-analysis:0.0.1-dev .
FROM pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime

RUN 
    apt-get update \
    && apt-get install -y git wget curl vim build-essential \
    && pip3 install transformers pandas numpy accelerate ir_datasets